PLV_lap02/PLV_lap02/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PLV_lap02.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PLV_lap02/PLV_lap02/Controllers/PLV_productsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PLV_lap02.Controllers
{
    public class PLV_productsController : Controller
    {
        // GET: PLV_products
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Musiclist()
        {
            return View();
        }
        public ActionResult PlayMusic(string songName)
        {
            string filePath = Url.Content("~/Content/" + songName + ".mp3");
            ViewBag.SongUrl = filePath;

            return View("MusicList");
        }
        public FileResult DownloadMusic(string id)
        {
            string filePath = Server.MapPath("~/Content/" + id + ".mp3");
            string contentType = "audio/mpeg";

            return File(filePath, contentType, id + ".mp3");
        }
    }
    

}

PLV_lap02/PLV_lap02/Views/PLV_products/Musiclist.cshtml
@{
    ViewBag.Title = "Musiclist";
}

<h2>Danh sách nhạc</h2>
<table>
    <tr>
        <th>Tên nhạc</th>
        <th>Tải về</th>
    </tr>
    <tr>
        <td><a href="@Url.Action("PlayMusic", "PLV_products", new { songName = "demo" })">Nhạc demo</a></td>
        <td><a href="@Url.Action("DownloadMusic", "PLV_products", new { id = "demo" })">Tải về</a></td>
    </tr>
    <tr>
        <td><a href="@Url.Action("PlayMusic", "PLV_products", new { songName = "demo2" })">Nhạc demo2</a></td>
        <td><a href="@Url.Action("DownloadMusic", "PLV_products", new { id = "demo2" })">Tải về</a></td>
    </tr>
    <tr>
        <td><a href="@Url.Action("PlayMusic", "PLV_products", new { songName = "demo3" })">Nhạc demo3</a></td>
        <td><a href="@Url.Action("DownloadMusic", "PLV_products", new { id = "demo3" })">Tải về</a></td>
    </tr>
</table>
<audio controls>
    <source src="@ViewBag.SongUrl" type="audio/mpeg">
</audio>

PLV_lap02/PLV_lap02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Nhạc", "Musiclist", "PLV_products")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>